-- ============================================================================
-- Reference/configuration data: document categories, loan products and the
-- default document checklist for each. All of this is admin-editable at
-- runtime from Settings — nothing here is hard-coded into app logic.
-- ============================================================================

insert into document_categories (code, name, folder_prefix, sequence) values
  ('KYC',           'KYC',                      '01_KYC',           1),
  ('APPLICATION',   'Application',              '02_APPLICATION',   2),
  ('FINANCIAL',     'Financial Documents',      '03_FINANCIAL',     3),
  ('SECURITY',      'Security / Property',      '04_SECURITY',      4),
  ('LOAN_SPECIFIC', 'Loan Specific',            '05_LOAN_SPECIFIC', 5),
  ('OTHER',         'Other',                    '06_OTHER',         6);

insert into loan_categories (code, name, description, sequence) values
  ('CC',           'Cash Credit',               'Working-capital cash credit facility secured by stock and book debts', 1),
  ('TERM_LOAN',    'Term Loan',                  'Medium/long term loan for capex or project financing', 2),
  ('HOME_LOAN',    'Home Loan',                  'Retail loan for purchase/construction of residential property', 3),
  ('EDUCATION_LOAN','Education Loan',            'Loan for higher education expenses', 4),
  ('MSME_LOAN',    'MSME Loan',                  'Loan facility for micro, small and medium enterprises', 5),
  ('WORKING_CAPITAL','Working Capital Loan',     'Short-term working capital finance', 6),
  ('VEHICLE_LOAN', 'Vehicle Loan',               'Loan for purchase of new/used vehicle', 7),
  ('PERSONAL_LOAN','Personal Loan',              'Unsecured retail personal loan', 8),
  ('MORTGAGE_LAP', 'Mortgage / Loan Against Property', 'Loan secured against mortgage of immovable property', 9),
  ('OTHER',        'Other',                      'Other/miscellaneous loan category', 10);

insert into branches (name, code, address) values
  ('MG Road Branch',    'BR-MGR-001', '12 MG Road, Bengaluru'),
  ('Andheri Branch',    'BR-AND-002', '45 SV Road, Mumbai'),
  ('Connaught Place Branch', 'BR-CNP-003', '9 CP Block, New Delhi');

-- ----------------------------------------------------------------------------
-- Document requirement matrix
-- ----------------------------------------------------------------------------
with req(loan_code, doc_cat_code, doc_name, doc_code, required, seq, keywords) as (
  values
  -- ============================== Cash Credit ==============================
  ('CC','KYC','PAN Card','KYC_PAN',true,1,array['permanent account number','income tax department','pan card']),
  ('CC','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar','unique identification authority','uidai']),
  ('CC','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof','utility bill','passport']),
  ('CC','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('CC','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('CC','APPLICATION','Loan Application Form','APP_FORM',true,1,array['loan application form','application for cash credit']),
  ('CC','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('CC','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('CC','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil','credit information']),
  ('CC','FINANCIAL','Income Tax Return','FIN_ITR',true,1,array['income tax return','itr','acknowledgement number']),
  ('CC','FINANCIAL','Balance Sheet','FIN_BALANCE_SHEET',true,2,array['balance sheet']),
  ('CC','FINANCIAL','Profit & Loss Account','FIN_PL',true,3,array['profit and loss','profit & loss']),
  ('CC','FINANCIAL','Bank Statement (Last 12 Months)','FIN_BANK_STMT',true,4,array['bank statement','account statement']),
  ('CC','FINANCIAL','GST Returns','FIN_GST',true,5,array['gst','goods and services tax','gstr']),
  ('CC','FINANCIAL','CMA Data','FIN_CMA',true,6,array['cma data','credit monitoring arrangement']),
  ('CC','SECURITY','Hypothecation of Stock & Book Debts','SEC_HYPOTHECATION',true,1,array['hypothecation']),
  ('CC','SECURITY','Collateral Security Documents','SEC_COLLATERAL',true,2,array['collateral']),
  ('CC','SECURITY','Guarantor KYC & Net Worth Statement','SEC_GUARANTOR',true,3,array['guarantor','net worth']),
  ('CC','SECURITY','Insurance of Stock','SEC_INSURANCE',true,4,array['insurance policy']),
  ('CC','LOAN_SPECIFIC','CC Application Form','LS_CC_APPLICATION',true,1,array['cash credit application']),
  ('CC','LOAN_SPECIFIC','Stock Statement','LS_CC_STOCK',true,2,array['stock statement']),
  ('CC','LOAN_SPECIFIC','Book Debt Statement','LS_CC_BOOKDEBT',true,3,array['book debt']),
  ('CC','LOAN_SPECIFIC','Working Capital Assessment Note','LS_CC_WC_NOTE',true,4,array['working capital assessment']),
  ('CC','LOAN_SPECIFIC','Drawing Power Calculation','LS_CC_DP',true,5,array['drawing power']),
  ('CC','LOAN_SPECIFIC','Renewal Request Letter','LS_CC_RENEWAL',true,6,array['renewal request']),
  ('CC','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Term Loan ==============================
  ('TERM_LOAN','KYC','PAN Card','KYC_PAN',true,1,array['permanent account number','pan card']),
  ('TERM_LOAN','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar','uidai']),
  ('TERM_LOAN','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('TERM_LOAN','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('TERM_LOAN','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('TERM_LOAN','APPLICATION','Term Loan Application Form','APP_FORM',true,1,array['term loan application']),
  ('TERM_LOAN','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('TERM_LOAN','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('TERM_LOAN','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('TERM_LOAN','FINANCIAL','Income Tax Return','FIN_ITR',true,1,array['income tax return','itr']),
  ('TERM_LOAN','FINANCIAL','Balance Sheet','FIN_BALANCE_SHEET',true,2,array['balance sheet']),
  ('TERM_LOAN','FINANCIAL','Profit & Loss Account','FIN_PL',true,3,array['profit and loss']),
  ('TERM_LOAN','FINANCIAL','Bank Statement (Last 12 Months)','FIN_BANK_STMT',true,4,array['bank statement']),
  ('TERM_LOAN','FINANCIAL','GST Returns','FIN_GST',true,5,array['gst','gstr']),
  ('TERM_LOAN','FINANCIAL','CMA Data','FIN_CMA',true,6,array['cma data']),
  ('TERM_LOAN','FINANCIAL','Projected Financial Statements','FIN_PROJECTED',true,7,array['projected financial']),
  ('TERM_LOAN','FINANCIAL','Statement of Other Liabilities','FIN_OTHER_LIAB',true,8,array['other liabilities']),
  ('TERM_LOAN','SECURITY','Sale Deed','SEC_SALE_DEED',true,1,array['sale deed']),
  ('TERM_LOAN','SECURITY','Title Documents','SEC_TITLE',true,2,array['title deed','title documents']),
  ('TERM_LOAN','SECURITY','Encumbrance Certificate','SEC_EC',true,3,array['encumbrance certificate']),
  ('TERM_LOAN','SECURITY','Valuation Report','SEC_VALUATION',true,4,array['valuation report']),
  ('TERM_LOAN','SECURITY','Legal Opinion','SEC_LEGAL_OPINION',true,5,array['legal opinion']),
  ('TERM_LOAN','SECURITY','Property Tax Receipt','SEC_TAX_RECEIPT',true,6,array['property tax receipt']),
  ('TERM_LOAN','SECURITY','Insurance','SEC_INSURANCE',true,7,array['insurance policy']),
  ('TERM_LOAN','LOAN_SPECIFIC','Term Loan Application','LS_TL_APPLICATION',true,1,array['term loan application']),
  ('TERM_LOAN','LOAN_SPECIFIC','Project Report','LS_TL_PROJECT_REPORT',true,2,array['project report']),
  ('TERM_LOAN','LOAN_SPECIFIC','Quotations','LS_TL_QUOTATIONS',true,3,array['quotation']),
  ('TERM_LOAN','LOAN_SPECIFIC','Projected Cash Flow','LS_TL_CASHFLOW',true,4,array['projected cash flow']),
  ('TERM_LOAN','LOAN_SPECIFIC','Machinery / Asset Purchase Invoice','LS_TL_ASSET_INVOICE',true,5,array['invoice']),
  ('TERM_LOAN','LOAN_SPECIFIC','Repayment Schedule Acknowledgement','LS_TL_REPAYMENT_SCHEDULE',true,6,array['repayment schedule']),
  ('TERM_LOAN','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Home Loan ==============================
  ('HOME_LOAN','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('HOME_LOAN','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('HOME_LOAN','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('HOME_LOAN','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('HOME_LOAN','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('HOME_LOAN','APPLICATION','Home Loan Application Form','APP_FORM',true,1,array['home loan application']),
  ('HOME_LOAN','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('HOME_LOAN','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('HOME_LOAN','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('HOME_LOAN','FINANCIAL','Salary Slips (Last 3 Months)','FIN_SALARY',true,1,array['salary slip','payslip']),
  ('HOME_LOAN','FINANCIAL','Form 16 / Income Tax Return','FIN_FORM16',true,2,array['form 16','income tax return']),
  ('HOME_LOAN','FINANCIAL','Bank Statement (Salary Account)','FIN_BANK_STMT',true,3,array['bank statement']),
  ('HOME_LOAN','FINANCIAL','Income Proof (Self-Employed)','FIN_INCOME_PROOF',true,4,array['income proof']),
  ('HOME_LOAN','SECURITY','Sale Agreement','SEC_SALE_AGREEMENT',true,1,array['sale agreement','agreement to sell']),
  ('HOME_LOAN','SECURITY','Title Documents','SEC_TITLE',true,2,array['title deed']),
  ('HOME_LOAN','SECURITY','Encumbrance Certificate','SEC_EC',true,3,array['encumbrance certificate']),
  ('HOME_LOAN','SECURITY','Valuation Report','SEC_VALUATION',true,4,array['valuation report']),
  ('HOME_LOAN','SECURITY','Legal Opinion','SEC_LEGAL_OPINION',true,5,array['legal opinion']),
  ('HOME_LOAN','SECURITY','Insurance','SEC_INSURANCE',true,6,array['insurance policy']),
  ('HOME_LOAN','LOAN_SPECIFIC','Home Loan Application','LS_HL_APPLICATION',true,1,array['home loan application']),
  ('HOME_LOAN','LOAN_SPECIFIC','Sanction Letter Acceptance','LS_HL_SANCTION_ACK',true,2,array['sanction letter']),
  ('HOME_LOAN','LOAN_SPECIFIC','Processing Fee Receipt','LS_HL_FEE_RECEIPT',true,3,array['processing fee']),
  ('HOME_LOAN','LOAN_SPECIFIC','NOC from Builder / Society','LS_HL_NOC',true,4,array['no objection certificate','noc']),
  ('HOME_LOAN','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Education Loan ==============================
  ('EDUCATION_LOAN','KYC','Student PAN Card','KYC_PAN',true,1,array['pan card']),
  ('EDUCATION_LOAN','KYC','Student Aadhaar / Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('EDUCATION_LOAN','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('EDUCATION_LOAN','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('EDUCATION_LOAN','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('EDUCATION_LOAN','APPLICATION','Education Loan Application Form','APP_FORM',true,1,array['education loan application']),
  ('EDUCATION_LOAN','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('EDUCATION_LOAN','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('EDUCATION_LOAN','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('EDUCATION_LOAN','FINANCIAL','Bank Statement (Last 6 Months)','FIN_BANK_STMT',true,1,array['bank statement']),
  ('EDUCATION_LOAN','FINANCIAL','Parent/Guardian Income Proof','FIN_INCOME_PROOF',true,2,array['income proof','salary certificate']),
  ('EDUCATION_LOAN','SECURITY','Collateral Documents (where applicable)','SEC_COLLATERAL',false,1,array['collateral']),
  ('EDUCATION_LOAN','LOAN_SPECIFIC','Education Loan Application','LS_EL_APPLICATION',true,1,array['education loan application']),
  ('EDUCATION_LOAN','LOAN_SPECIFIC','Parent / Guardian KYC','LS_EL_PARENT_KYC',true,2,array['parent kyc','guardian kyc']),
  ('EDUCATION_LOAN','LOAN_SPECIFIC','Admission Letter','LS_EL_ADMISSION_LETTER',true,3,array['admission letter','offer letter']),
  ('EDUCATION_LOAN','LOAN_SPECIFIC','Fee Structure','LS_EL_FEE_STRUCTURE',true,4,array['fee structure']),
  ('EDUCATION_LOAN','LOAN_SPECIFIC','Academic Certificates','LS_EL_ACADEMIC_CERTS',true,5,array['academic certificate','marksheet']),
  ('EDUCATION_LOAN','LOAN_SPECIFIC','Co-Applicant Declaration','LS_EL_CO_APPLICANT',true,6,array['co-applicant']),
  ('EDUCATION_LOAN','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== MSME Loan ==============================
  ('MSME_LOAN','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('MSME_LOAN','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('MSME_LOAN','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('MSME_LOAN','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('MSME_LOAN','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('MSME_LOAN','APPLICATION','MSME Loan Application Form','APP_FORM',true,1,array['msme loan application']),
  ('MSME_LOAN','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('MSME_LOAN','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('MSME_LOAN','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('MSME_LOAN','FINANCIAL','Income Tax Return','FIN_ITR',true,1,array['income tax return']),
  ('MSME_LOAN','FINANCIAL','Balance Sheet','FIN_BALANCE_SHEET',true,2,array['balance sheet']),
  ('MSME_LOAN','FINANCIAL','Profit & Loss Account','FIN_PL',true,3,array['profit and loss']),
  ('MSME_LOAN','FINANCIAL','Bank Statement (Last 12 Months)','FIN_BANK_STMT',true,4,array['bank statement']),
  ('MSME_LOAN','FINANCIAL','GST Returns','FIN_GST',true,5,array['gst']),
  ('MSME_LOAN','FINANCIAL','CMA Data','FIN_CMA',true,6,array['cma data']),
  ('MSME_LOAN','SECURITY','Collateral Security Documents','SEC_COLLATERAL',true,1,array['collateral']),
  ('MSME_LOAN','SECURITY','Insurance','SEC_INSURANCE',true,2,array['insurance policy']),
  ('MSME_LOAN','SECURITY','Guarantor KYC & Net Worth Statement','SEC_GUARANTOR',true,3,array['guarantor']),
  ('MSME_LOAN','LOAN_SPECIFIC','MSME Loan Application','LS_MSME_APPLICATION',true,1,array['msme application']),
  ('MSME_LOAN','LOAN_SPECIFIC','Udyam Registration Certificate','LS_MSME_UDYAM',true,2,array['udyam registration']),
  ('MSME_LOAN','LOAN_SPECIFIC','Business Profile','LS_MSME_PROFILE',true,3,array['business profile']),
  ('MSME_LOAN','LOAN_SPECIFIC','Machinery Quotation','LS_MSME_QUOTATION',true,4,array['quotation']),
  ('MSME_LOAN','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Working Capital ==============================
  ('WORKING_CAPITAL','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('WORKING_CAPITAL','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('WORKING_CAPITAL','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('WORKING_CAPITAL','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('WORKING_CAPITAL','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('WORKING_CAPITAL','APPLICATION','Working Capital Application Form','APP_FORM',true,1,array['working capital application']),
  ('WORKING_CAPITAL','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('WORKING_CAPITAL','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('WORKING_CAPITAL','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('WORKING_CAPITAL','FINANCIAL','Income Tax Return','FIN_ITR',true,1,array['income tax return']),
  ('WORKING_CAPITAL','FINANCIAL','Balance Sheet','FIN_BALANCE_SHEET',true,2,array['balance sheet']),
  ('WORKING_CAPITAL','FINANCIAL','Profit & Loss Account','FIN_PL',true,3,array['profit and loss']),
  ('WORKING_CAPITAL','FINANCIAL','Bank Statement (Last 12 Months)','FIN_BANK_STMT',true,4,array['bank statement']),
  ('WORKING_CAPITAL','FINANCIAL','GST Returns','FIN_GST',true,5,array['gst']),
  ('WORKING_CAPITAL','FINANCIAL','CMA Data','FIN_CMA',true,6,array['cma data']),
  ('WORKING_CAPITAL','SECURITY','Hypothecation of Stock & Book Debts','SEC_HYPOTHECATION',true,1,array['hypothecation']),
  ('WORKING_CAPITAL','SECURITY','Collateral Security Documents','SEC_COLLATERAL',true,2,array['collateral']),
  ('WORKING_CAPITAL','SECURITY','Insurance','SEC_INSURANCE',true,3,array['insurance policy']),
  ('WORKING_CAPITAL','LOAN_SPECIFIC','Working Capital Application','LS_WC_APPLICATION',true,1,array['working capital application']),
  ('WORKING_CAPITAL','LOAN_SPECIFIC','Stock Statement','LS_WC_STOCK',true,2,array['stock statement']),
  ('WORKING_CAPITAL','LOAN_SPECIFIC','Book Debt Statement','LS_WC_BOOKDEBT',true,3,array['book debt']),
  ('WORKING_CAPITAL','LOAN_SPECIFIC','Working Capital Assessment Note','LS_WC_ASSESSMENT',true,4,array['working capital assessment']),
  ('WORKING_CAPITAL','LOAN_SPECIFIC','Drawing Power Calculation','LS_WC_DP',true,5,array['drawing power']),
  ('WORKING_CAPITAL','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Vehicle Loan ==============================
  ('VEHICLE_LOAN','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('VEHICLE_LOAN','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('VEHICLE_LOAN','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('VEHICLE_LOAN','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('VEHICLE_LOAN','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('VEHICLE_LOAN','APPLICATION','Vehicle Loan Application Form','APP_FORM',true,1,array['vehicle loan application']),
  ('VEHICLE_LOAN','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('VEHICLE_LOAN','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('VEHICLE_LOAN','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('VEHICLE_LOAN','FINANCIAL','Bank Statement (Last 6 Months)','FIN_BANK_STMT',true,1,array['bank statement']),
  ('VEHICLE_LOAN','FINANCIAL','Income Proof','FIN_INCOME_PROOF',true,2,array['income proof']),
  ('VEHICLE_LOAN','SECURITY','Insurance','SEC_INSURANCE',true,1,array['insurance policy']),
  ('VEHICLE_LOAN','SECURITY','Vehicle RC & Hypothecation','SEC_RC_HYPOTHECATION',true,2,array['registration certificate','hypothecation']),
  ('VEHICLE_LOAN','LOAN_SPECIFIC','Vehicle Loan Application','LS_VL_APPLICATION',true,1,array['vehicle loan application']),
  ('VEHICLE_LOAN','LOAN_SPECIFIC','Vehicle Quotation / Proforma Invoice','LS_VL_QUOTATION',true,2,array['proforma invoice','quotation']),
  ('VEHICLE_LOAN','LOAN_SPECIFIC','Driving License','LS_VL_LICENSE',true,3,array['driving licence','driving license']),
  ('VEHICLE_LOAN','LOAN_SPECIFIC','Vehicle Registration Certificate','LS_VL_RC',true,4,array['registration certificate']),
  ('VEHICLE_LOAN','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Personal Loan ==============================
  ('PERSONAL_LOAN','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('PERSONAL_LOAN','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('PERSONAL_LOAN','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('PERSONAL_LOAN','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('PERSONAL_LOAN','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('PERSONAL_LOAN','APPLICATION','Personal Loan Application Form','APP_FORM',true,1,array['personal loan application']),
  ('PERSONAL_LOAN','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('PERSONAL_LOAN','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('PERSONAL_LOAN','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('PERSONAL_LOAN','FINANCIAL','Bank Statement (Last 6 Months)','FIN_BANK_STMT',true,1,array['bank statement']),
  ('PERSONAL_LOAN','FINANCIAL','Salary Slips (Last 3 Months)','FIN_SALARY',true,2,array['salary slip']),
  ('PERSONAL_LOAN','FINANCIAL','Form 16','FIN_FORM16',true,3,array['form 16']),
  ('PERSONAL_LOAN','LOAN_SPECIFIC','Personal Loan Application','LS_PL_APPLICATION',true,1,array['personal loan application']),
  ('PERSONAL_LOAN','LOAN_SPECIFIC','Employment Certificate','LS_PL_EMPLOYMENT_CERT',true,2,array['employment certificate']),
  ('PERSONAL_LOAN','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Mortgage / LAP ==============================
  ('MORTGAGE_LAP','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('MORTGAGE_LAP','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('MORTGAGE_LAP','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('MORTGAGE_LAP','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('MORTGAGE_LAP','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('MORTGAGE_LAP','APPLICATION','Loan Against Property Application Form','APP_FORM',true,1,array['loan against property application']),
  ('MORTGAGE_LAP','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('MORTGAGE_LAP','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('MORTGAGE_LAP','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('MORTGAGE_LAP','FINANCIAL','Income Tax Return','FIN_ITR',true,1,array['income tax return']),
  ('MORTGAGE_LAP','FINANCIAL','Bank Statement (Last 12 Months)','FIN_BANK_STMT',true,2,array['bank statement']),
  ('MORTGAGE_LAP','FINANCIAL','Balance Sheet','FIN_BALANCE_SHEET',true,3,array['balance sheet']),
  ('MORTGAGE_LAP','FINANCIAL','Profit & Loss Account','FIN_PL',true,4,array['profit and loss']),
  ('MORTGAGE_LAP','SECURITY','Sale Deed','SEC_SALE_DEED',true,1,array['sale deed']),
  ('MORTGAGE_LAP','SECURITY','Title Documents','SEC_TITLE',true,2,array['title deed']),
  ('MORTGAGE_LAP','SECURITY','Encumbrance Certificate','SEC_EC',true,3,array['encumbrance certificate']),
  ('MORTGAGE_LAP','SECURITY','Valuation Report','SEC_VALUATION',true,4,array['valuation report']),
  ('MORTGAGE_LAP','SECURITY','Legal Opinion','SEC_LEGAL_OPINION',true,5,array['legal opinion']),
  ('MORTGAGE_LAP','SECURITY','Property Tax Receipt','SEC_TAX_RECEIPT',true,6,array['property tax receipt']),
  ('MORTGAGE_LAP','SECURITY','Insurance','SEC_INSURANCE',true,7,array['insurance policy']),
  ('MORTGAGE_LAP','LOAN_SPECIFIC','Loan Against Property Application','LS_LAP_APPLICATION',true,1,array['loan against property']),
  ('MORTGAGE_LAP','LOAN_SPECIFIC','Property Search Report','LS_LAP_SEARCH_REPORT',true,2,array['search report']),
  ('MORTGAGE_LAP','LOAN_SPECIFIC','NOC from Existing Lender','LS_LAP_NOC',true,3,array['no objection certificate','noc']),
  ('MORTGAGE_LAP','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[]),

  -- ============================== Other ==============================
  ('OTHER','KYC','PAN Card','KYC_PAN',true,1,array['pan card']),
  ('OTHER','KYC','Aadhaar / Officially Valid Identity Document','KYC_AADHAAR',true,2,array['aadhaar']),
  ('OTHER','KYC','Address Proof','KYC_ADDRESS',true,3,array['address proof']),
  ('OTHER','KYC','Photograph','KYC_PHOTO',true,4,array['photograph']),
  ('OTHER','KYC','Signature Verification','KYC_SIGNATURE',true,5,array['signature']),
  ('OTHER','APPLICATION','Loan Application Form','APP_FORM',true,1,array['loan application form']),
  ('OTHER','APPLICATION','Application Annexure','APP_ANNEXURE',true,2,array['annexure']),
  ('OTHER','APPLICATION','Customer Declaration','APP_DECLARATION',true,3,array['declaration']),
  ('OTHER','APPLICATION','Consent Form (Credit Bureau)','APP_CONSENT',true,4,array['consent','cibil']),
  ('OTHER','FINANCIAL','Bank Statement','FIN_BANK_STMT',true,1,array['bank statement']),
  ('OTHER','FINANCIAL','Income Tax Return','FIN_ITR',true,2,array['income tax return']),
  ('OTHER','LOAN_SPECIFIC','Loan Application','LS_OTHER_APPLICATION',true,1,array['application']),
  ('OTHER','LOAN_SPECIFIC','Supporting Documents','LS_OTHER_SUPPORTING',true,2,array['supporting document']),
  ('OTHER','OTHER','Other Supporting Document','OTH_GENERIC',false,1,array[]::text[])
)
insert into document_requirements
  (loan_category_id, document_category_id, document_name, code, required, sequence, classification_keywords)
select lc.id, dc.id, r.doc_name, r.doc_code, r.required, r.seq, r.keywords
from req r
join loan_categories lc on lc.code = r.loan_code
join document_categories dc on dc.code = r.doc_cat_code;
